export const facultyData = [
  "Sharmila Banu K",
  "Anisha M Lal",
  "Ayyasamy S",
  "R M Brisilla",
  "Kalaavathi B",
  "Lavanya K",
  "Mariappan R",
  "Ramanathan L",
  "Saleem Durai M A",
  "Sendhil Kumar KS",
  "Srimathi",
  "Venkata Lakshmi Narayana K",
  "Vijayarajan V",
  "Viswanathan P",
  "Rajkumar S",
  "Balamurugan R",
  "Chellatamilan T",
  "Dheeba J",
  "Jeevanantham AK",
  "Joshva Devadas T",
  "Kakelli Anil Kumar",
  "Kathiravan S",
  "Lakshmanan K",
  "Madiajagan M",
  "Malathi M",
  "Priya G",
  "Rajakumar K",
  "Rajkumar R",
  "Santhi K",
  "Sudha S",
  "Vimaladevi K",
  "Gopinath M.P",
  "Balasubramanian",
  "Boominathan P",
  "Kalyanaraman P",
  "Madhu Viswanatham V",
  "Mohan K",
  "Natarajan P",
  "RA. K. Saravanaguru",
  "Rajeshkannan",
  "Saravanan R",
  "Sathyaraj R",
  "Senthilkumar K",
  "Swarnalatha P",
  "Vijayakumar K",
  "Murali S",
  "Anuradha J",
  "Arunkumar T",
  "Gayathri P",
  "Geetha Mary",
  "Manikandan K",
  "Manikandan N",
  "Monash P",
  "Narayanan Prasanth N",
  "H Parveen Sultana",
  "Rajay Vedaraj I S",
  "Sivaprasad Darla",
  "Subramaniyaswamy",
  "Sudhakara Pandian R",
  "Swathi J N",
  "S L Aarthy",
  "Ananda Kumar S",
  "Arivarasu M",
  "Chandramohan B",
  "Debi Prasanna Acharjya",
  "Dega Nagaraju",
  "Jothi K R",
  "Madhuri W",
  "Rajasekhara Babu M",
  "Ramesh Babu K R",
  "Rhymend Uthariaraj V",
  "Sathiya Kumar C",
  "Sasikala R",
  "Shashank Mouli Satapathy",
  "Umadevi K S",
  "Jaisankar N",
  "Anthoniraj A",
  "Govinda K",
  "Gunavathi C",
  "Kumar K",
  "Manjula R",
  "Margret Anouncia S",
  "Mohanasundaram R",
  "Mythili T",
  "Sanjiban Sekhar Roy",
  "Sathis Kumar B",
  "Shobha Rekh",
  "S Vairamuthu",
  "Anusha N",
  "Ilayaraja V",
  "Kanagaraj K",
  "Karthikeyan A",
  "Lakshmi S",
  "Narayanamoorthi M",
  "Naresh K",
  "J Saira Banu",
  "Satyajit Mohanty",
  "Yokesh Babu S",
  "Adaline Suji R",
  "Anny Leema",
  "Balakrishnan P",
  "Biji C L",
  "S Ebenezer Juliet",
  "Jayakumar K",
  "Jenicka S",
  "Keerthika P",
  "Lokesh Kumar R",
  "Mary Mekala A",
  "Radhakrishnan Delhibabu",
  "Ramesh C",
  "Rajan Shrivastava",
  "P Senthilnathan",
  "Sharief Basha S",
  "Sivakumar T",
  "Subramanyam Reddy A",
  "Thirumoorthy K",
  "Varalakshmi M",
  "D Aju",
  "Anbarasi M",
  "Arthi M",
  "Devipriya A",
  "Nalliah M",
  "G M Karthik",
  "Kaspar S",
  "Raja S P",
  "Ramani S",
  "Saravanarajan M C",
  "Sivakumar N",
  "Sudarshan Nandy",
  "Viswanathan A",
  "Yuvaraj N",
  "Abdul Gaffar H",
  "Ilanthenral K P S K",
  "Jayashree J",
  "Kumaresan A",
  "Mehfooza M",
  "P Mohankumar",
  "Nageshwar Rao Ragi",
  "Prabakaran N",
  "Prakash G",
  "Ramesh Babu Vemuluri",
  "Ruby D",
  "Santhi H",
  "Selvi M",
  "Sinthuja M",
  "Suresh P",
  "Thanuja R",
  "J Vijayashree",
  "S Anto",
  "Arivoli A",
  "Balaji GN",
  "Berlin M A",
  "Chiranjeevi C",
  "Geraldine Bessie Amali D",
  "Jyotismita Chaki",
  "Naga Raja G",
  "Nagaraja Rao A",
  "Navamani T M",
  "Naveenkumar J",
  "Prakash M",
  "S Sreethar",
  "Suresh A",
  "D Ajitha",
  "Akila Victor",
  "Anindita Kundu",
  "Annapurna J",
  "Arun Kumar G",
  "Badrinath N",
  "Divya Meena S",
  "Jayakumar S",
  "R Kannadasan",
  "Keyur B Joshi",
  "Nithya N S",
  "Perepi Rajarajeswari",
  "Saravanakumar K",
  "Sarwesh P",
  "Satish C.J",
  "Siva Shanmugam G",
  "Vijayasherly V",
  "Srihari Mandava",
  "S Vinila Jinny",
  "Adrija Bhattacharya",
  "Allam Jaya Prakash",
  "Arumuga Arun R",
  "Baiju B V",
  "Bhuvaneswari M",
  "Deepikaa S",
  "Gayathri S",
  "Gunasekar M",
  "Jafar Ali Ibrahim S",
  "Jim Solomon Raja D",
  "Lydia Jane G",
  "Manoov R",
  "Muthunagai S U",
  "Nalini N",
  "Pooja Chaudhary",
  "Priyanka N",
  "Pushpa Gothwal",
  "Ragavan K",
  "Raviteja Buddala",
  "Saranya P",
  "Satyajit Das",
  "Sharmila C",
  "Sivanesan S",
  "Sridhar Raj S",
  "Sri Preethaa K R",
  "Srivani A",
  "Thamizharasan S",
  "Ushus Elizebeth Zachariah",
  "Vetriselvi",
  "Harini N",
  "Saraswathi U",
  "Anitha R",
  "Deepa D",
  "Dhinakaran N",
  "Dinesh P",
  "Katari Balakrishna",
  "Nagaraj S",
  "Balaji N",
  "Dilip Kumar S",
  "Diviya M",
  "Kamanasish Bhattacharjee",
  "Karthik K",
  "Muchenedihari Kishor",
  "Mukhtar Ahmad Sofi",
  "Naga Priyadarsini R",
  "Parthiban K",
  "S Ranjithkumar",
  "Reya Sharma",
  "Saraswathi Priyadharshini A",
  "Sivaranjani A",
  "Siva Sankari S",
  "Sivakumar V",
  "Suganthini C",
  "Swetha NG",
  "Yoganand S",
  "Kaushik Hariharan G",
  "Debarati Dutta",
  "Deepika S",
  "Keerthika C",
  "Kurra Sai Susheel",
  "Megala G",
  "Pandiaraj A",
  "Vasanthi P",
  "Arun Prasath G",
  "Banupriya R",
  "Bhulakshmi Bonthu",
  "Chandru Vignesh C",
  "Deepika J",
  "Ezhil Arasi V",
  "Islabudeen M",
  "Gopichand G",
  "Gopinath M",
  "Kanagaraj R",
  "Manikandan G",
  "Mohankumar B",
  "Niha Kamal Basha",
  "Parthasarathy G",
  "Poornima",
  "S M Prabin",
  "Priyadharsini M",
  "Rishin Haldar",
  "Samriddhi Sarkar",
  "S Sridevi",
  "Somasundaram S K",
  "Thangaramya K",
  "Raghul J",
  "Anusha R",
  "Jayachandran J",
  "Manas Gautam",
  "Vusirikkayala Gowthami",
  "Archana T",
  "Arulkumar V",
  "Ganesh Khekare",
  "Dhivyaa C R",
  "Goutam Majumder",
  "Kalaivani K",
  "Kauser Ahmed P",
  "Praveen Kumar G",
  "Konatham Sumalatha",
  "Kovendan A K P",
  "Krishnaraj N",
  "Madhan E S",
  "Meenakshi S P",
  "Naveen Kumar N",
  "Padmavathy T",
  "Rakhi Mol V",
  "Ranjith R",
  "Saritha Murali",
  "Sathya K",
  "Saurabh Agrawal",
  "Sayan Sikder",
  "Sunil Kumar",
  "Tamizharasi T",
  "Vinothsaravanan R",
  "Swetha V",
  "Latha Reddy N",
  "Maheswari B",
  "Naramalli Jayakrishna",
  "Pavithra M",
  "Raparthi Yaswanth",
  "Revathi C K",
  "Rohini S",
  "Tamilmani A",
  "Anand Bihari",
  "Antony Seba P",
  "Arpita Ghosh",
  "Athira K",
  "Baskaran P",
  "Bhawana Tyagi",
  "S. M. Farooq",
  "Hiteshwar Kumar Azad",
  "Iyappan Perumal",
  "Jagalingam Pushparaj",
  "Jayalakshmi M",
  "Justin Gopinath A",
  "Kopperundevi N",
  "Krishna Rani Samal K",
  "Malini S",
  "Mohamed Yousuff A.R",
  "Mohana C M",
  "Murugan Krishnamoorthy",
  "Nithya K",
  "Rajarajan G",
  "Sudhakar P",
  "Sujatha V",
  "Sukantha Ghosh",
  "Thirunavukkarasan M",
  "Umamaheswari M",
  "Uma Priya D",
  "Vishnu Priya A",
  "Rohith R",
  "Bharath Babu S",
  "Munusamy S",
  "Nivethitha K",
  "Pasupuleti Muniraja",
  "Syamasudha Veeragandham",
  "Anuradha D",
  "Anuradha G",
  "Arpan Garai",
  "Deepa D",
  "Deepa K",
  "Durgesh Kumar",
  "Gladys Gnana Kiruba B",
  "Jabanjalin Hilda",
  "Jaya Subalakshmi R",
  "Karthika M S",
  "Krishnamoorthy A",
  "Mohana Sundari L",
  "Nivitha K",
  "Padma Priya R",
  "Shalini L",
  "Sivaprakash S",
  "Soumyajyoti Dey",
  "Sunija A P",
  "Tamizhselvi S P",
  "Vani Rajasekar",
  "Anandita Iyer A",
  "Ankareddy Rajesh",
  "Lakshmi S",
  "Sripriyanka G",
];
